packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@nestjs/core": true
  "@prisma/engines": true
  prisma: true
  "@tailwindcss/oxide": true
  esbuild: true
  unrs-resolver: true
  bcrypt: true

minimumReleaseAgeExclude:
  - tsx@4.22.3
